name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/apps/mahayojana-backend || exit 1

            # Pull latest changes
            git pull origin main

            # Install dependencies including dev dependencies
            npm install --include=dev

            # Build the project
            npm run build

            # Ensure environment variables are set in PM2
            if [ -f .env ]; then
              # Restart with environment variables from .env
              pm2 restart mahayojana-backend --update-env || pm2 start ecosystem.config.js
            else
              echo "Warning: .env file not found!"
              exit 1
            fi

            # Reload Nginx (ignore errors if it fails)
            sudo systemctl reload nginx || true
